#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# To eliminate verbosity
alias \
	cim="nvim ~/.config/nvim/init.vim" \
	tmc="tremc" \
	nf="neofetch" \
	uf="ufetch" \
	covid="curl https://corona-stats.online/" \
	bat="cat /sys/class/power_supply/BAT0/capacity" \
	yt="youtube-dl -ic --add-metadata" \
	ytm="youtube-dl -i -x -c --add-metadata -f bestaudio" \
	ytr="youtube-dl --rm-cache-dir" \
	str="straw-viewer --resolution=720p" \
    cs="config status" \
    cg="config" \
	gs="git status" \
    gl="git log" \
	untar="tar -xzvf" \
	gnu="gnuplot" \
	scr="cd ~/.local/bin; ls ./" \
	htspt="sudo create_ap wlo1 eno1 heisenberg420 yellpassword" \
	nc="ncmpcpp" \
	b="buku --suggest" \
	yt7="yt -i --add-metadata -f 247+251" \
	yt8="yt -i --add-metadata -f 248+251" \
	cbs="checkbashisms" \
	rd="redshift -P -O 4000" \
	sxiv="sxiv -b" \
	bsv="Rscript -e \"blogdown::serve_site()\" ; hugo server" \
	hs="hugo server" \
	R="R --silent" \
    jn="jupyter-notebook" \
    nnn="nnn -d -e" \
    emc="nvim ~/.emacs.d/init.el"

# Colorize commands when possible and increase verbosity
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -A" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	mv="mv -vi" \
	rm="rm -vI" \
	cp="cp -v" \
	..="cd .." \
	:q="exit" \

# Common commands to abbreviate
alias \
	vim="nvim" \
	pu="sudo pacman -Syu --color always" \
	pi="sudo pacman -S" \
	prs="sudo pacman -Rns" \
	sc="sc-im" \
    ytt="youtube-dl -ic --add-metadata --all-subs https://www.youtube.com/playlist?list=PLOFEBzvs-VvqPzAH4jwcHbV_rJz2_l9B6" \

se(){ du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
