#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"


# To eliminate verbosity
alias \
	cvim="nvim ~/.config/nvim/init.vim" \
	cw="fortune | cowsay | lolcat" \
	mb="mbsync -a" \
	uf="ufetch" \
	corona="curl https://corona-stats.online/" \
	bat="cat /sys/class/power_supply/BAT0/capacity" \
	yt="youtube-dl -i --add-metadata -i" \
	ytm="youtube-dl -i --add-metadata -f bestaudio" \
	ytr="youtube-dl --rm-cache-dir" \
	gs="git status" \
	untar="tar -xzvf" \
	gnu="gnuplot" \
	scr="cd ~/.local/bin/" \
	htspt="sudo create_ap wlo1 eno1 heisenberg420 yellpassword" \
	nc="ncmpcpp" \
	# wth="pkill -RTMIN+5 dwmblocks" \  # updates weather module of dwmblocks


# Colorize commands when possible and increase verbosity
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -A" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	mv="mv -iv" \
	rm="rm -iv" \
	cp="cp -v" \
	..="cd .." \
	:q="exit" \
	

# Common commands to abbreviate
alias \
	vim="nvim" \
	pu="sudo pacman -Syu --color always" \
	pi="sudo pacman -S" \
	pr="sudo pacman -Rs" \
	sc="sc-im" \


se(){ du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}

