#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# To eliminate verbosity
alias \
	cim="nvim ~/.config/nvim/init.vim" \
	tmc="tremc" \
	nf="neofetch" \
	uf="uptime -p" \
	covid="curl https://corona-stats.online/" \
	bat0="cat /sys/class/power_supply/BAT0/capacity" \
	yt="youtube-dl -ic --add-metadata" \
	ytm="youtube-dl -i -x -c --add-metadata -f bestaudio" \
	ytr="youtube-dl --rm-cache-dir" \
	str="pipe-viewer --resolution=720p" \
    ytf="ytfzf -t" \
	gnu="gnuplot" \
	scr="cd ~/.local/bin; ls ./" \
	hotspot="sudo create_ap wlo1 eno1 heisenberg420 yellpassword" \
	b="buku --suggest" \
	yt7="yt -i --add-metadata -f 247+251" \
	yt8="yt -i --add-metadata -f 248+251" \
    tv7="mpv --ytdl-format=22" \
    tv8="mpv --ytdl-format=248+251" \
	cbs="checkbashisms" \
	sxiv="sxiv -b" \
	bsv="Rscript -e \"blogdown::serve_site()\" ; hugo server" \
    R="R --silent" \
    r="radian" \
	hs="hugo server" \
    jd="julia -ie 'using Franklin; serve()'" \
    jn="jupyter-notebook" \
    ipy="ipython" \
    ka="killall" \
    py="python" \
    jl="julia" \
    tmux="tmux -f ~/.config/tmux/tmux.conf" \
    smc="sudo make clean install" \

# Git aliases
alias \
    lg="lazygit" \
	gs="git status" \
    ga="git add" \
    gc="git commit" \
    cs="cfg status" \
    gd="git diff" \
    gb="git branch" \
    gf="git fetch" \
    gm="git merge" \
    gp="git push" \

# Colorize commands when possible and increase verbosity
alias \
    ls="ls --group-directories-first --color=always" \
	la="ls -a" \
    ll="ls -l" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	mv="mv -vi" \
	rm="rm -vI" \
    rmdir="rmdir -v" \
	cp="cp -v" \
	..="cd .." \
	:q="exit" \
	# ls="ls -hN --color=always --group-directories-first" \

# Common commands to abbreviate
alias \
	vim="nvim" \
	pu="sudo pacman -Syu --color always" \
	pi="sudo pacman -S" \
	prs="sudo pacman -Rns" \
	sc="sc-im" \
    svim="sudoedit nvim" \
    qtm="tmuxp load ~/.config/tmuxp/mysession.yaml" \
    stm="tmuxp load ~/.config/tmuxp/qiskit-sessions.yaml" \
    cq="cd ~/misc/git-repos/progs/qiskit/ && . ./venv/bin/activate" \
    qblogin="ssh -L 3000:localhost:3000 ubuntu@ec2-52-65-167-232.ap-southeast-2.compute.amazonaws.com" \

se(){ du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
